/**
 * Represents configurations for a wide range of device types including traditional computing devices, 
 * entertainment systems, wearable tech, and Internet of Things (IoT) devices.
 * Each device configuration includes properties specific to the device type, such as screen attributes, user agent, etc.
 *
 * @type {Object}
 * @property {DeviceConfigurations} phone - Collection of smartphone configurations.
 * @property {DeviceConfigurations} tablet - Collection of tablet configurations.
 * @property {DeviceConfigurations} notebook - Collection of notebook configurations.
 * @property {DeviceConfigurations} desktop - Collection of desktop computer configurations.
 * @property {DeviceConfigurations} watch - Collection of smartwatch configurations.
 * @property {DeviceConfigurations} television - Collection of smart TV configurations.
 * @property {DeviceConfigurations} browser - Collection of browser configurations.
 * 
 * @typedef {Object.<string, DeviceConfiguration>} DeviceConfigurations
 * 
 * @typedef {Object} DeviceConfiguration
 * @property {string} title - Device name.
 */
export const DeviceList = {
  phone: {
    appleIphone15ProMax: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 430,
          logicalHeight: 932,
          safeAreaInsets: {
            left: 0,
            top: 59,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 932,
          logicalHeight: 430,
          safeAreaInsets: {
            left: 59,
            top: 0,
            right: 59,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 15 Pro Max (2023)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 15 Pro Max',
        platform: 'iOS',
        platformVersion: '17.2',
      },
      useDeviceMockup: 'phoneIphone14Pro15',
      useIcon: 'phoneIphone15',
    },
    appleIphone15: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 393,
          logicalHeight: 852,
          safeAreaInsets: {
            left: 0,
            top: 59,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 852,
          logicalHeight: 393,
          safeAreaInsets: {
            left: 59,
            top: 0,
            right: 59,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 15 (2023)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 15',
        platform: 'iOS',
        platformVersion: '17.2',
      },
      useDeviceMockup: 'phoneIphone14Pro15',
      useIcon: 'phoneIphone',
    },
    appleIphone14ProMax: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 430,
          logicalHeight: 932,
          safeAreaInsets: {
            left: 0,
            top: 59,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 932,
          logicalHeight: 430,
          safeAreaInsets: {
            left: 59,
            top: 0,
            right: 59,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 14 Pro Max (2022)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 14 Pro Max',
        platform: 'iOS',
        platformVersion: '16.6',
      },
      useDeviceMockup: 'phoneIphone14Pro15',
      useIcon: 'phoneIphone',
    },
    appleIphone14Pro: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 430,
          logicalHeight: 932,
          safeAreaInsets: {
            left: 0,
            top: 59,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 932,
          logicalHeight: 430,
          safeAreaInsets: {
            left: 59,
            top: 0,
            right: 59,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 14 Pro (2022)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 14 Pro',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'phoneIphone14Pro15',
      useIcon: 'phoneIphone',
    },    
    appleIphone13Pro: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 390,
          logicalHeight: 844,
          safeAreaInsets: {
            left: 0,
            top: 47,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 844,
          logicalHeight: 390,
          safeAreaInsets: {
            left: 47,
            top: 0,
            right: 47,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 13 Pro (2021)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 13 Pro',
        platform: 'iOS',
        platformVersion: '15.0',
      },
      useDeviceMockup: 'phoneIphone13',
      useIcon: 'phoneIphone',
    },
    appleIphone13Mini: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 390,
          logicalHeight: 844,
          safeAreaInsets: {
            left: 0,
            top: 50,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 844,
          logicalHeight: 390,
          safeAreaInsets: {
            left: 50,
            top: 0,
            right: 50,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 13 Mini (2021)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 13',
        platform: 'iOS',
        platformVersion: '15.0',
      },
      useDeviceMockup: 'phoneIphone13',
      useIcon: 'phoneIphone',
    },
    appleIphone13: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 390,
          logicalHeight: 844,
          safeAreaInsets: {
            left: 0,
            top: 47,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 844,
          logicalHeight: 390,
          safeAreaInsets: {
            left: 47,
            top: 0,
            right: 47,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 13 (2021)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 13',
        platform: 'iOS',
        platformVersion: '15.0',
      },
      useDeviceMockup: 'phoneIphone13',
      useIcon: 'phoneIphone',
    },
    appleIphone12Pro: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 390,
          logicalHeight: 844,
          safeAreaInsets: {
            left: 0,
            top: 47,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 844,
          logicalHeight: 390,
          safeAreaInsets: {
            left: 47,
            top: 0,
            right: 47,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone 12 Pro (2020)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone 12 Pro',
        platform: 'iOS',
        platformVersion: '14.0',
      },
      useDeviceMockup: 'phoneIphone12',
      useIcon: 'phoneIphone',
    },
    appleIphoneSE2022: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 375,
          logicalHeight: 667,
          safeAreaInsets: {
            left: 0,
            top: 20,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 667,
          logicalHeight: 375,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPhone SE (2022)',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPhone SE (2022)',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneIphone',
    },
    asusZenfone10: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Asus Zenfone 10 (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; ASUS Zenfone 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Asus',
        mobile: true,
        model: 'Zenfone 10',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phone',
    },
    onePlus12: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'OnePlus 12 (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; ONEPLUS A5010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'OnePlus',
        mobile: true,
        model: 'OnePlus 12',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phone',
    },
    samsungGalaxyS24Ultra: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 4,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy S24 Ultra (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-S928U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'Galaxy S24 Ultra',
        platform: 'Android',
        platformVersion: '14',
      },
      useDeviceMockup: 'phoneSamsungGalaxyS24Ultra',
      useIcon: 'phoneAndroid',
    },
    samsungGalaxyS23Ultra: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 4,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy S23 Ultra (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-S918U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-S918U',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    samsungGalaxyS23: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 4,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy S23 (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-S911U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-S911U',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    samsungGalaxyS22: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 4,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy S22 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-S901U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-S901U',
        platform: 'Android',
        platformVersion: '12',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    samsungGalaxyS21: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 4,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy S21 (2021)',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-G991U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-G991U',
        platform: 'Android',
        platformVersion: '11',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    samsungGalaxyZFlip5: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: true,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 360,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 360,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Z Flip 5 (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-F731U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'Galaxy Z Flip 5',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    googlePixel8Pro: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel 8 Pro (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel 8 Pro',
        platform: 'Android',
        platformVersion: '14',
      },
      useDeviceMockup: 'phoneGooglePixel8Pro',
      useIcon: 'phoneAndroid',
    },    
    googlePixel7Pro: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel 7 Pro (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel 7 Pro',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    googlePixel7: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel 7 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel 7',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    googlePixel6: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel 6 (2021)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel 6',
        platform: 'Android',
        platformVersion: '12',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
    googlePixel5: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 412,
          logicalHeight: 915,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 915,
          logicalHeight: 412,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel 5 (2020)',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel 5',
        platform: 'Android',
        platformVersion: '11',
      },
      useDeviceMockup: 'phone',
      useIcon: 'phoneAndroid',
    },
  },
  tablet: {
    appleIpadPro129: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 1024,
          logicalHeight: 1366,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 1366,
          logicalHeight: 1024,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPad Pro 12.9-inch (2022)',
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPad Pro 12.9-inch',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletMac',
    },
    appleIpadPro11: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 834,
          logicalHeight: 1194,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 1194,
          logicalHeight: 834,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPad Pro 11-inch (2022)',
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPad Pro 11-inch',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletMac',
    },
    appleIpadAir5: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 820,
          logicalHeight: 1180,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 1180,
          logicalHeight: 820,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPad Air (5th generation, 2022)',
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPad Air',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletMac',
    },
    appleIpad10thGen: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 810,
          logicalHeight: 1080,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
        horizontal: {
          logicalWidth: 1080,
          logicalHeight: 810,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPad (10th generation, 2022)',
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPad',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletMac',
    },
    appleIpadMini6: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 768,
          logicalHeight: 1024,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1024,
          logicalHeight: 768,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iPad Mini (6th generation, 2021)',
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'iPad Mini',
        platform: 'iOS',
        platformVersion: '16.1',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletMac',
    },
    googlePixelTablet: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1280,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Google Pixel Tablet (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; Pixel Tablet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Google',
        mobile: true,
        model: 'Pixel Tablet',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tabletAndroid',
    },
    lenovoTabP11Pro: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 1600,
          logicalHeight: 2560,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 2560,
          logicalHeight: 1600,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Lenovo Tab P11 Pro (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; Lenovo TB-J706F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Lenovo',
        mobile: true,
        model: 'TB-J706F',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    onePlusPad: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1400,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1400,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'OnePlus Pad (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; KB2000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'OnePlus',
        mobile: true,
        model: 'KB2000',
        platform: 'Android',
        platformVersion: '14',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    samsungGalaxyTabS9Ultra: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1280,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Tab S9 Ultra (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-T990) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-T990',
        platform: 'Android',
        platformVersion: '14',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    samsungGalaxyTabS8Ultra: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 1600,
          logicalHeight: 2560,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 2560,
          logicalHeight: 1600,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Tab S8 Ultra (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-T920) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-T920',
        platform: 'Android',
        platformVersion: '13',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    samsungGalaxyTabS8: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1280,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Tab S8 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-X700) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-X700',
        platform: 'Android',
        platformVersion: '12',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    samsungGalaxyTabS7: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1280,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 3,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Tab S7 (2020)',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-T870) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'SM-T870',
        platform: 'Android',
        platformVersion: '11',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    microsoftSurfacePro9: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 900,
          logicalHeight: 1200,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1200,
          logicalHeight: 900,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Microsoft Surface Pro 9 (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Microsoft',
        mobile: false,
        model: 'Surface Pro 9',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
    microsoftSurfaceGo3: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 800,
          logicalHeight: 1200,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 20,
          },
        },
        horizontal: {
          logicalWidth: 1200,
          logicalHeight: 800,
          safeAreaInsets: {
            left: 0,
            top: 24,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Microsoft Surface Go 3 (2021)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Microsoft',
        mobile: false,
        model: 'Surface Go 3',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'tablet',
      useIcon: 'tablet',
    },
  },  
  notebook: {
    appleMacBookPro2021: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1800,
          logicalHeight: 1440,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple MacBook Pro (14-inch, 16-inch, 2021)',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: false,
        model: 'MacBook Pro',
        platform: 'Mac OS X',
        platformVersion: '11.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebookMac',
    },
    appleMacBookAir2022: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1680,
          logicalHeight: 1050,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple MacBook Air (M2, 2022)',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: false,
        model: 'MacBook Air',
        platform: 'Mac OS X',
        platformVersion: '12.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebookMac',
    },
    dellXPS15: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1920,
          logicalHeight: 1080,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Dell XPS 15 (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Dell',
        mobile: false,
        model: 'XPS 15',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebook',
    },
    hpSpectreX360: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1920,
          logicalHeight: 1080,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HP Spectre x360 (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'HP',
        mobile: false,
        model: 'Spectre x360',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebook',
    },
    microsoftSurfaceLaptop5: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 2496,
          logicalHeight: 1664,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Microsoft Surface Laptop 5 (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Microsoft',
        mobile: false,
        model: 'Surface Laptop 5',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebookWindows',
    },
    lenovoThinkPadX1Carbon: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1920,
          logicalHeight: 1200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Lenovo ThinkPad X1 Carbon (10th generation, 2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Lenovo',
        mobile: false,
        model: 'ThinkPad X1 Carbon',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'notebook',
      useIcon: 'notebook',
    },
  },
  desktop: {
    appleIMac24: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 4480,
          logicalHeight: 2520,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple iMac 24-inch (2021)',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: false,
        model: 'iMac 24-inch',
        platform: 'Mac OS X',
        platformVersion: '11.0',
      },
      useDeviceMockup: 'desktop',
      useIcon: 'desktop',
    },
    microsoftSurfaceStudio2Plus: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 4500,
          logicalHeight: 3000,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Microsoft Surface Studio 2+ (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Microsoft',
        mobile: false,
        model: 'Surface Studio 2+',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'desktop',
      useIcon: 'desktop',
    },
    hpEnvyAllInOne: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HP Envy All-in-One (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'HP',
        mobile: false,
        model: 'Envy All-in-One',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'desktop',
      useIcon: 'desktop',
    },
    dellXPSDesktop: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Dell XPS Desktop (2022)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
      userAgentMetadata: {
        brand: 'Dell',
        mobile: false,
        model: 'XPS Desktop',
        platform: 'Windows',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'desktop',
      useIcon: 'desktop',
    },
  },
  watch: {
    appleWatchSeries9: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch Series 9 (2023)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 10_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/10.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch Series 9',
        platform: 'watchOS',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    appleWatchUltra2: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch Ultra 2 (2023)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 10_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/10.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch Ultra 2',
        platform: 'watchOS',
        platformVersion: '10.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    appleWatchSeries8: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch Series 8 (2022)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 9_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/9.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch Series 8',
        platform: 'watchOS',
        platformVersion: '9.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    appleWatchSeries7: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch Series 7 (2021)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 8_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/8.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch Series 7',
        platform: 'watchOS',
        platformVersion: '8.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    appleWatchSE2022: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch SE (2022)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 9_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/9.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch SE',
        platform: 'watchOS',
        platformVersion: '9.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    appleWatchUltra: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 198,
          logicalHeight: 242,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Apple Watch Ultra (2022)',
      userAgent: 'Mozilla/5.0 (Apple Watch; CPU WatchOS 9_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/9.0 Mobile/15E148 Safari/604.1',
      userAgentMetadata: {
        brand: 'Apple',
        mobile: true,
        model: 'Watch Ultra',
        platform: 'watchOS',
        platformVersion: '9.0',
      },
      useDeviceMockup: 'watch',
      useIcon: 'watch',
    },
    samsungGalaxyWatch6: {
      isActive: true,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 200,
          logicalHeight: 200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Watch 6 (2023)',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-R930) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'Galaxy Watch 6',
        platform: 'Wear OS',
        platformVersion: '4.0',
      },
      useDeviceMockup: 'watchGalaxy',
      useIcon: 'watch',
    },
    samsungGalaxyWatch5: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 200,
          logicalHeight: 200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Watch 5 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-R910) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'Galaxy Watch 5',
        platform: 'Wear OS',
        platformVersion: '3.5',
      },
      useDeviceMockup: 'watchGalaxy',
      useIcon: 'watch',
    },
    samsungGalaxyWatch4: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 200,
          logicalHeight: 200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung Galaxy Watch 4 (2021)',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-R860) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: true,
        model: 'Galaxy Watch 4',
        platform: 'Wear OS',
        platformVersion: '3.0',
      },
      useDeviceMockup: 'watchGalaxy',
      useIcon: 'watch',
    },
    fitbitSense2: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 336,
          logicalHeight: 336,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Fitbit Sense 2 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; Fitbit Sense 2) AppleWebKit/537.36 (KHTML, like Gecko) Version/12.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Fitbit',
        mobile: true,
        model: 'Sense 2',
        platform: 'Fitbit OS',
        platformVersion: '5.1',
      },
      useDeviceMockup: 'watchFitbit',
      useIcon: 'watch',
    },
    fitbitVersa4: {
      isActive: false,
      capabilities: ['touch', 'mobile'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'vertical',
      modes: {
        vertical: {
          logicalWidth: 336,
          logicalHeight: 336,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'vertical',
      screen: {
        clut: 0,
        colorDepth: 16,
        devicePixelRatio: 2,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Fitbit Versa 4 (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; Fitbit Versa 4) AppleWebKit/537.36 (KHTML, like Gecko) Version/12.0 Mobile Safari/537.36',
      userAgentMetadata: {
        brand: 'Fitbit',
        mobile: true,
        model: 'Versa 4',
        platform: 'Fitbit OS',
        platformVersion: '5.1',
      },
      useDeviceMockup: 'watchFitbit',
      useIcon: 'watch',
    },
  },
  television: {
    samsungQLED: {
      isActive: false,
      capabilities: ['touch', 'television'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Samsung QLED TV (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Tizen 6.5; SAMSUNG QLED TV) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 TV Safari/537.36',
      userAgentMetadata: {
        brand: 'Samsung',
        mobile: false,
        model: 'QLED TV',
        platform: 'Tizen',
        platformVersion: '6.5',
      },
      useDeviceMockup: 'television',
      useIcon: 'television',
    },
    lgOLED: {
      isActive: false,
      capabilities: ['touch', 'television'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'LG OLED TV (2022)',
      userAgent: 'Mozilla/5.0 (WebOS; LG OLED TV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Safari/537.36',
      userAgentMetadata: {
        brand: 'LG',
        mobile: false,
        model: 'OLED TV',
        platform: 'webOS',
        platformVersion: '6.0',
      },
      useDeviceMockup: 'television',
      useIcon: 'television',
    },
    sonyBravia: {
      isActive: false,
      capabilities: ['touch', 'television'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'Sony Bravia TV (2022)',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; BRAVIA 4K GB) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Safari/537.36',
      userAgentMetadata: {
        brand: 'Sony',
        mobile: false,
        model: 'Bravia',
        platform: 'Android',
        platformVersion: '10',
      },
      useDeviceMockup: 'television',
      useIcon: 'television',
    },
    tclRokuTV: {
      isActive: false,
      capabilities: ['touch', 'television'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'TCL Roku TV (2022)',
      userAgent: 'Mozilla/5.0 (Linux; U; Android 10; TCL Roku TV) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.96 Safari/537.36',
      userAgentMetadata: {
        brand: 'TCL',
        mobile: false,
        model: 'Roku TV',
        platform: 'Android',
        platformVersion: '10',
      },
      useDeviceMockup: 'television',
      useIcon: 'television',
    },
  },
  display: {
    QVGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 320,
          logicalHeight: 240,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'QVGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    VGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 640,
          logicalHeight: 480,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'VGA (NTSC square)',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    PAL: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 768,
          logicalHeight: 576,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'PAL (square)',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    SVGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 800,
          logicalHeight: 600,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'SVGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    qHD: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 960,
          logicalHeight: 540,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'qHD',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    XGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1024,
          logicalHeight: 768,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'XGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    HDTV_720: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 720,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HDTV 720',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    SXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1280,
          logicalHeight: 1024,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'SXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    HD: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1366,
          logicalHeight: 768,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HD',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    SXGAPlus: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1400,
          logicalHeight: 1050,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'SXGA+',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WSXGA: {
      isActive: true,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1440,
          logicalHeight: 900,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WSXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    HDPlus: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1600,
          logicalHeight: 900,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HD+ 900p',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    UXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1600,
          logicalHeight: 1200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'UXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WXGAPlusPlus: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1680,
          logicalHeight: 945,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WXGA++',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WSXGAPlus: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1680,
          logicalHeight: 1050,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WSXGA+',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    HDTV_1080: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1920,
          logicalHeight: 1080,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'HDTV 1080, FullHD',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WUXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 1920,
          logicalHeight: 1200,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WUXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    QXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 2048,
          logicalHeight: 1536,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'QXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WQXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 2560,
          logicalHeight: 1600,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WQXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    QFHD_4K_UltraHD: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2160,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'QFHD, 4K, UltraHD',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
    WQUXGA: {
      isActive: false,
      capabilities: ['display'],
      dualScreen: false,
      foldableScreen: false,
      iconOrientationByDefault: 'horizontal',
      modes: {
        horizontal: {
          logicalWidth: 3840,
          logicalHeight: 2400,
          safeAreaInsets: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
        },
      },
      orientationByDefault: 'horizontal',
      screen: {
        clut: 0,
        colorDepth: 24,
        devicePixelRatio: 1,
        grid: 0,
        mediaType: 'screen',
        monochrome: 0,
        scan: null,
      },
      title: 'WQUXGA',
      userAgent: '',
      userAgentMetadata: {
        brand: '',
        mobile: false,
        model: '',
        platform: '',
        platformVersion: '',
      },
      useDeviceMockup: 'display',
      useIcon: 'display',
    },
  }
};