/**
 * Defines UI themes with style properties for various components like background, toolbar, ruler, and grid.
 * 
 * @type {Object}
 * @property {Object} dark - Dark theme configuration.
 * @property {Object} light - Light theme configuration.
 */
export const Themes = {
  dark: {
    name: 'Dark',
    breakpointBevelSize: '0.3125em',
    breakpointGap: '0.125em',
    colorBackground: '#151515',
    colorBackgroundDragHandle: '#444',
    colorBackgroundDropdown: '#282828',
    colorBackgroundRuler: 'rgba(53, 54, 58, 0.8)',
    colorBackgroundRulerMarker: '#fff',
    colorBackgroundSelection: '#1ED760',
    colorBackgroundToolbar: '#000000',
    colorBorderInput: '#383838',
    colorBreakpointText: '#fff',
    colorError: '#d71e1e',
    colorGrid: 'rgba(255, 255, 255, 0.1)',
    colorGridSecondary: 'rgba(255, 255, 255, 0.05)',
    colorHeading: '#fff',
    colorRulerMarkerText: '#000',
    colorRulerText: '#fff',
    colorSelectionText: '#000',
    colorSuccess: '#1ED760',
    colorText: '#a9a9a9',
    colorTextActive: '#1ED760',
    colorTextHover: '#fff',
    fontFamilyDefault: 'system-ui, Arial, sans-serif',
    fontFamilyMonospace: 'monospace',
    sizeBaseFont: '16px',
    sizeBreakpoint: '1.625rem',
    sizeBreakpointFont: '0.75em',
    sizeDragHandle: '1rem',
    sizeH1Font: '1.75em',
    sizeH2Font: '1.25em',
    sizeH3Font: '1.125em',
    sizeRuler: '2rem',
    sizeRulerFont: '0.625rem',
    sizeToolbar: '3.5rem',
    sizeToolbarFont: '0.9375rem',
    unicodeBidi: 'normal',
  },
  light: {
    name: 'Light',
    breakpointBevelSize: '0.3125em',
    breakpointGap: '0.125em',
    colorBackground: '#eee',
    colorBackgroundDragHandle: '#ccc',
    colorBackgroundDropdown: '#eee',
    colorBackgroundRuler: 'rgba(225, 225, 225, 0.8)',
    colorBackgroundRulerMarker: '#000',
    colorBackgroundSelection: '#119944',
    colorBackgroundToolbar: '#fff',
    colorBorderInput: '#ccc',
    colorBreakpointText: '#fff',
    colorError: '#d71e1e',
    colorGrid: 'rgba(0, 0, 0, 0.1)',
    colorGridSecondary: 'rgba(0, 0, 0, 0.05)',
    colorHeading: '#000',
    colorRulerMarkerText: '#fff',
    colorRulerText: '#000',
    colorSelectionText: '#fff',
    colorSuccess: '#1ED760',
    colorText: '#000',
    colorTextActive: '#119944',
    colorTextHover: '#555',
    fontFamilyDefault: 'system-ui, Arial, sans-serif',
    fontFamilyMonospace: 'monospace',
    sizeBaseFont: '16px',
    sizeBreakpoint: '1.625rem',
    sizeBreakpointFont: '0.75em',
    sizeDragHandle: '1rem',
    sizeH1Font: '1.75em',
    sizeH2Font: '1.25em',
    sizeH3Font: '1.125em',
    sizeRuler: '2rem',
    sizeRulerFont: '0.625rem',
    sizeToolbar: '3.5rem',
    sizeToolbarFont: '0.9375rem',
    unicodeBidi: 'normal',
  },
};